apiVersion: apps/v1
kind: Deployment
metadata:
  name: jretest
spec:
  selector:
    matchLabels:
      app: jretest
  replicas: 1
  template:
    metadata:
      name: jretest
      labels:
        app: jretest
    spec:
      imagePullSecrets:
      - name: gcr-secret
      containers:
      - name: jretest
        image: gcr.io/git-ops-automation/helloworld:e60c28e8f3004985e3d36700ea8f5cc187a1bf9d
        ports:
        - containerPort: 8080
