apiVersion: apps/v1
kind: Deployment
metadata:
  name: jretest
spec:
  selector:
    matchLabels:
      app: jretest
  replicas: 1
  template:
    metadata:
      name: jretest
      labels:
        app: jretest
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: jretest
        image: gcr.io/git-ops-automation/helloworld:35889a2f063809a2ca91252f2a25e0a64630016e
        ports:
        - containerPort: 80
