apiVersion: apps/v1
kind: Deployment
metadata:
  name: jretest
spec:
  selector:
    matchLabels:
      app: jretest
  replicas: 1
  template:
    metadata:
      name: jretest
      labels:
        app: jretest
    spec:
      containers:
      - name: jretest
        image: gcr.io/git-ops-automation/helloworld:
        ports:
        - containerPort: 80
