apiVersion: v1
kind: Service
metadata:
  name: jretest
  labels:
    run: jretest
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30475
    targetPort: 8080
    protocol: TCP
  selector:
    run: jretest
