apiVersion: v1
kind: Service
metadata:
  name: jretest
  labels:
    run: jretest
spec:
  ports:
  - port: 7000
    targetPort: 8080
    nodePort: 30036
    protocol: TCP
  selector:
    run: jretest
