# This is a basic workflow to help you get started with Actions

name: CI Repository Dispatch

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
#  schedule:
    # * is a special character in YAML so you have to quote this string
#    - cron:  '*/15 * * * *'

  repository_dispatch:
    types: [kubernetes-event]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}
      - run: echo ${{ github.event.client_payload.sha }}
